In [1]:
# %pip install numpy

In [2]:
import numpy as np

## Extra: Custom Dataset Generation

| Syntax              |  Name 
| :---                | :--  
| `x[0]`              | **Index**
| `x[1:3]`            | **Slice**
| `x[0] = 5`          | **Mutate**
| `x[0:4] = 5`        | **Mutate**
| `y = x * 5`         | **Transform**
| `x[3:] = x[3:] * 5` | **Transform In-Place**
| `x[3:] *= 5`        | **Transform In-Place** (shorter version)



Without hard-coding it, create an array with these values: `[ 0, 99,  2, 99,  4, 99, 6, 99,  8, 99]`

In [58]:
x = np.arange(10)
x[1::2]=99
x

array([ 0, 99,  2, 99,  4, 99,  6, 99,  8, 99])

Without hard-coding it, create an array with these values:
`[  0, 100, 200, 300,   4,   5,   6,   7,   8,   9]`

In [61]:
x = np.arange(10)
x[1:4] *= 100
x

array([  0, 100, 200, 300,   4,   5,   6,   7,   8,   9])

## Numpy Arrays

#### Some Array Creation Functions (Review)
| Function | Purpose |  Example |
| :-----------: | :-------------: | :-------------: |
| **np.array()**  | Turns a list into an array |   `np.array([2, 5, 3])` |
| **np.arange()**                  | the integers between two values | `np.arange(2, 7)` |
| **np.arange()**                  | the numbers between two values, with a given step size | `np.arange(2, 7, 0.5)` |
| **np.linspace()**               | a given number of values between two values |  `np.linspace(2, 3, 10)` |
| **np.zeros()**                    | Makes an array of all zeros | `np.zeros(5)` |
| **np.ones()**                     | Makes an array of all ones | `np.ones(3)` |
| **np.random.random()** | Makes an array of random numbers | `np.random.random(100)` |
| **np.random.randn()**     | Makes an array of normally-distributed random numbers | `np.random.randn(100)` |
| **np.random.randint()**     | Makes an array of uniformly-distributed random integers | `np.random.randint(-5, 10, 100)` |


#### Important Array Attributes

| Attribute     | Description                                          | Example Output   |
| :-------:     | :---------:                                          | :-----:          |
| **`x.dtype`**  | numpy data type (64-bit int, 32-bit float, etc)      | `dtype('int64')` | 
| **`x.shape`**  | number of elements along each dimension of the array | `(17,)`          |
| **`x.size`**   | total number of values in the array                  | `17`             | 
| **`x.nbytes`** | total amount of memory the array takes up, in bytes  | `136`            |



**Exercises**

Make the arrays requested in any way you'd like, then print the property requested from that created array.

**Example: All the integers from 3 to 10**

In [15]:
x = np.arange(3, 11)
x

array([ 3,  4,  5,  6,  7,  8,  9, 10])

How many total values are in this array?

In [16]:
x.size

8

**All the numbers from 2 to 6, spaced 0.3 apart.**

In [62]:
x = np.arange(2, 6, 0.3)
x

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9])

What is the shape of this array?

In [18]:
x.shape

(17,)

**9 numbers from 3 to 6, spaced equally apart.**

In [22]:
x = np.linspace(3, 6, 9)
x

array([3.   , 3.375, 3.75 , 4.125, 4.5  , 4.875, 5.25 , 5.625, 6.   ])

How many bytes does this array take up?

In [24]:
x.nbytes

72

**The square of the values 40, 20, 3, 5, and 10.**

In [26]:
x = np.array([40, 20, 3, 5, 10])
x * x

array([1600,  400,    9,   25,  100])

What data type does this array hold?

In [27]:
x.dtype

dtype('int64')

**The square root of the values 32, 4, 3, and 6**

In [30]:
x = np.array([32, 4, 3, 6])
np.sqrt(x)

array([5.65685425, 2.        , 1.73205081, 2.44948974])

What data type does this array hold?

In [31]:
x.dtype

dtype('int64')

**Ten random integers between -3 and 3**

In [64]:
x = np.random.randint(-3, 3, 10)
x

array([-3, -1, -3, -2,  1,  2,  2, -3, -1,  1])

What is this array's shape?

In [36]:
x.shape

(10,)

**Create an array of the following five three-letter animal names: dog, cat, pig, rat, ant**

In [39]:
x = np.array(['dog','cat','pig','rat','ant'])


What data type does this array hold?

In [40]:
x.dtype

dtype('<U3')

How many bytes does this array take up?  Why?

In [41]:
x.nbytes

60

**Create an array of the following five animal names: dog, cat, pig, rat, anteater**

In [44]:
x = np.array(['dog','cat','pig','rat','anteater'])


What data type does this array hold?

In [47]:
x.dtype

dtype('<U8')

How many bytes does this array take up?  Why?

In [46]:
x.nbytes

160

## Extra: Custom Dataset Generation

| Syntax              |  Name 
| :---                | :--  
| `x[0]`              | **Index**
| `x[1:3]`            | **Slice**
| `x[0] = 5`          | **Mutate**
| `x[0:4] = 5`        | **Mutate**
| `y = x * 5`         | **Transform**
| `x[3:] = x[3:] * 5` | **Transform In-Place**
| `x[3:] *= 5`        | **Transform In-Place** (shorter version)



array([ 0, 99,  2, 99,  4, 99,  6, 99,  8, 99])

array([  0, 100, 200, 300,   4,   5,   6,   7,   8,   9])